apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-coffee
  labels:
    app: nginx
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx:latest
        resources:
          requests:
            cpu: "100m"
            memory: "100Mi"
            hyq.com/coffee: "1"
          limits:
            cpu: "100m"
            memory: "100Mi"
            hyq.com/coffee: "1"