apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: coffee-device-plugin
  labels:
    app: coffee-device-plugin
spec:
  selector:
    matchLabels:
      app: coffee-device-plugin
  template:
    metadata:
      labels:
        app: coffee-device-plugin
    spec:
      containers:
      - name: coffee-device-plugin
        image: quay.io/huyiqiu1998/coffee-device-plugin:v0.0.1
        volumeMounts:
        - name: device-plugin
          mountPath: /var/lib/kubelet/device-plugins
      volumes:
      - name: device-plugin
        hostPath:
          path: /var/lib/kubelet/device-plugins
      tolerations:
      - key: "CriticalAddonsOnly"
        operator: "Exists"
      - key: node.kubernetes.io/not-ready
        operator: Exists
        effect: NoExecute
      - key: node.kubernetes.io/unreachable
        operator: Exists
        effect: NoExecute